import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowUpRight, BedDouble, CalendarDays, Check, ChevronDown, CircleDollarSign, Eye, EyeOff, Hotel, LayoutDashboard, LogOut, Menu, Pencil, Plus, Search, Settings, Trash2, UserRound, Users, X } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import './App.css'

type Status = 'Belum Check In' | 'Sudah Check In'
type Section = 'dashboard' | 'orders' | 'customers' | 'settings'
type User = { name: string; role: string; initials: string; email: string; expiresAt?: number }
type Reservation = { id: string; nama: string; hotel: string; harga: number; kamar: number; checkIn: Date; checkOut: Date; jamMasuk: string; nomorHp: string; status: Status }
type FormState = { nama: string; hotel: string; harga: string; kamar: string; checkIn: string; checkOut: string; jamMasuk: string; nomorHp: string; status: Status }
type StoredReservation = Omit<Reservation, 'checkIn' | 'checkOut'> & { checkIn: string; checkOut: string }

const builtInAccounts: Record<string, User & { password: string }> = {
  'admin@nafya.com': { name: 'Aditya Rahman', role: 'Administrator', initials: 'AR', email: 'admin@nafya.com', password: 'admin123' },
  'manager@nafya.com': { name: 'Nadia Pratama', role: 'Hotel Manager', initials: 'NP', email: 'manager@nafya.com', password: 'manager123' },
}
const emptyForm: FormState = { nama: '', hotel: '', harga: '', kamar: '1', checkIn: '', checkOut: '', jamMasuk: '14:00', nomorHp: '', status: 'Belum Check In' }
const rupiah = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 })
const dateFormat = new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' })
const SESSION_DURATION = 24 * 60 * 60 * 1000
const protectedPaths = new Set(['/', '/customers', '/orders', '/settings'])

function App() {
  const location = useLocation()
  const navigate = useNavigate()
  const [user, setUser] = useState<User | null>(null)
  const [authReady, setAuthReady] = useState(false)
  const [reservations, setReservations] = useState<Reservation[]>([])
  const [loadedEmail, setLoadedEmail] = useState<string | null>(null)
  const [loginError, setLoginError] = useState('')
  const [login, setLogin] = useState({ email: 'admin@nafya.com', password: 'admin123' })
  const [section, setSection] = useState<Section>(() => sectionFromPath(window.location.pathname))
  const [filter, setFilter] = useState<'Semua' | Status>('Semua')
  const [settings, setSettings] = useState(loadSettings)
  const [form, setForm] = useState<FormState>(emptyForm)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [detail, setDetail] = useState<Reservation | null>(null)
  const [modal, setModal] = useState(false)
  const [sidebar, setSidebar] = useState(false)

  useEffect(() => {
    try {
      const rawSession = localStorage.getItem('nafya-user')
      if (rawSession) {
        const parsed = JSON.parse(rawSession) as User
        if (!parsed.email || !parsed.expiresAt || Date.now() >= parsed.expiresAt) {
          localStorage.removeItem('nafya-user')
        } else {
          setUser(parsed)
        }
      }
    } catch {
      localStorage.removeItem('nafya-user')
    } finally {
      setAuthReady(true)
    }
  }, [])

  useEffect(() => {
    if (!user) { setReservations([]); setLoadedEmail(null); return }
    setReservations(loadReservations(user.email))
    setLoadedEmail(user.email)
  }, [user?.email])
  useEffect(() => {
    if (user && loadedEmail === user.email) localStorage.setItem(bookingKey(user.email), JSON.stringify(reservations))
  }, [loadedEmail, reservations, user])
  useEffect(() => { localStorage.setItem('nafya-settings', JSON.stringify(settings)); document.body.classList.toggle('compact-mode', settings.compact) }, [settings])
  useEffect(() => {
    if (!user?.expiresAt) return
    const timeout = window.setTimeout(() => { localStorage.removeItem('nafya-user'); setUser(null); navigate('/login', { replace: true }) }, Math.max(0, user.expiresAt - Date.now()))
    return () => window.clearTimeout(timeout)
  }, [navigate, user?.expiresAt])

  const stats = useMemo(() => ({ revenue: reservations.reduce((sum, item) => sum + item.harga, 0), rooms: reservations.reduce((sum, item) => sum + item.kamar, 0), checkedIn: reservations.filter((item) => item.status === 'Sudah Check In').length }), [reservations])
  const filtered = useMemo(() => reservations.filter((item) => filter === 'Semua' || item.status === filter), [reservations, filter])
  const trend = useMemo(() => {
    const latestCheckIn = reservations.reduce<Date | null>((latest, item) => !latest || item.checkIn > latest ? item.checkIn : latest, null)
    const anchor = latestCheckIn ? new Date(latestCheckIn) : new Date()
    anchor.setHours(0, 0, 0, 0)
    return Array.from({ length: 7 }, (_, index) => {
      const day = new Date(anchor)
      day.setDate(anchor.getDate() - 6 + index)
      const dayKey = localDateKey(day)
      return { day: day.toLocaleDateString('id-ID', { day: '2-digit', month: 'short' }), value: reservations.filter((item) => localDateKey(item.checkIn) === dayKey).reduce((sum, item) => sum + item.harga / 1000000, 0) }
    })
  }, [reservations])

  const logout = () => { setUser(null); localStorage.removeItem('nafya-user'); navigate('/login', { replace: true }) }
  const loginSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { const accounts = JSON.parse(localStorage.getItem('nafya-accounts') || '{}') as Record<string, User & { password: string }>; const account = builtInAccounts[login.email] || accounts[login.email]; if (!account || account.password !== login.password) { setLoginError('Email atau password salah.'); return }; const session = { name: account.name, role: account.role, initials: account.initials, email: account.email, expiresAt: Date.now() + SESSION_DURATION }; setUser(session); localStorage.setItem('nafya-user', JSON.stringify(session)); const from = (location.state as { from?: { pathname?: string; search?: string } } | null)?.from; navigate(from?.pathname ? `${from.pathname}${from.search || ''}` : '/', { replace: true }) } catch { localStorage.removeItem('nafya-user'); setLoginError('Sesi login tidak dapat diproses. Silakan coba lagi.') } }
  const registerSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { const data = new FormData(event.currentTarget); const name = String(data.get('name')); const email = String(data.get('email')).toLowerCase(); const password = String(data.get('password')); const accounts = JSON.parse(localStorage.getItem('nafya-accounts') || '{}') as Record<string, User & { password: string }>; if (builtInAccounts[email] || accounts[email]) { setLoginError('Email sudah terdaftar.'); return }; const account = { name, role: 'Administrator', initials: name.split(' ').map((word) => word[0]).join('').slice(0, 2).toUpperCase(), email, password }; accounts[email] = account; localStorage.setItem('nafya-accounts', JSON.stringify(accounts)); const session = { ...account, expiresAt: Date.now() + SESSION_DURATION }; setUser(session); localStorage.setItem('nafya-user', JSON.stringify(session)); navigate('/', { replace: true }) } catch { localStorage.removeItem('nafya-user'); setLoginError('Registrasi tidak dapat diproses. Silakan coba lagi.') } }
  const navigateSection = (next: Section) => { setSection(next); setSidebar(false); navigate(sectionPath(next)) }
  const openAdd = () => { setEditingId(null); setForm(emptyForm); setModal(true) }
  const openEdit = (item: Reservation) => { setEditingId(item.id); setForm({ nama: item.nama, hotel: item.hotel, harga: formatPriceInput(item.harga), kamar: String(item.kamar), checkIn: item.checkIn.toISOString().slice(0, 10), checkOut: item.checkOut.toISOString().slice(0, 10), jamMasuk: item.jamMasuk, nomorHp: item.nomorHp, status: item.status }); setModal(true) }
  const saveReservation = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const price = parsePrice(form.harga); if (!form.nama || !form.hotel || !price || !form.checkIn || !form.checkOut || !form.nomorHp) return; const item: Reservation = { id: editingId || `NF-${String(Date.now()).slice(-4)}`, nama: form.nama, hotel: form.hotel, harga: price, kamar: Number(form.kamar), checkIn: new Date(form.checkIn), checkOut: new Date(form.checkOut), jamMasuk: form.jamMasuk, nomorHp: form.nomorHp, status: form.status }; setReservations((items) => editingId ? items.map((current) => current.id === editingId ? item : current) : [...items, item]); setModal(false) }
  useEffect(() => { setSection(sectionFromPath(location.pathname)) }, [location.pathname])

  if (!authReady) return <div className="auth-loading" role="status">Memuat sesi...</div>
  if (!user) { if (location.pathname === '/register') return <RegisterScreen onSubmit={registerSubmit} />; if (location.pathname === '/login') return <LoginScreen login={login} setLogin={setLogin} error={loginError} onSubmit={loginSubmit} />; return <AuthGuard user={user} /> }
  if (location.pathname === '/login' || location.pathname === '/register') return <Navigate to="/" replace />
  if (!protectedPaths.has(location.pathname)) return <NotFound />
  return <div className="app-shell"><Sidebar user={user} section={section} settings={settings} count={reservations.length} open={sidebar} onNavigate={navigateSection} onLogout={logout} /><main className="main-content"><header className="topbar"><button className="icon-button menu-button" type="button" onClick={() => setSidebar(!sidebar)} aria-label="Buka navigasi"><Menu size={21} /></button><div className="breadcrumb">{section === 'dashboard' ? 'Overview' : section === 'orders' ? 'Data Pesanan' : section === 'customers' ? 'Customers' : 'Pengaturan'} <ChevronDown size={14} /></div><div className="topbar-actions"><div className="avatar">{user.initials}</div><div className="admin-meta"><strong>{user.name}</strong><span>{user.role}</span></div></div></header><div className="page-content">{section === 'dashboard' && <Dashboard stats={stats} trend={trend} reservations={filtered} onAdd={openAdd} onOrders={() => navigateSection('orders')} onDelete={(id) => setReservations((items) => items.filter((item) => item.id !== id))} onDetail={setDetail} />}{section === 'orders' && <OrdersPage reservations={filtered} filter={filter} setFilter={setFilter} onAdd={openAdd} onEdit={openEdit} onDelete={(id) => setReservations((items) => items.filter((item) => item.id !== id))} onDetail={setDetail} />}{section === 'customers' && <CustomersPage reservations={reservations} onEdit={openEdit} onDelete={(id) => setReservations((items) => items.filter((item) => item.id !== id))} />}{section === 'settings' && <SettingsPage settings={settings} setSettings={setSettings} onLogout={logout} />}</div></main>{modal && <ReservationModal editing={Boolean(editingId)} form={form} setForm={setForm} onClose={() => setModal(false)} onSubmit={saveReservation} />}{detail && <DetailModal item={detail} onClose={() => setDetail(null)} />}</div>
}

function bookingKey(email: string) { return `hotelBookings_${encodeURIComponent(email.trim().toLowerCase())}` }
function sectionPath(section: Section) { return section === 'dashboard' ? '/' : `/${section}` }
function sectionFromPath(pathname: string): Section { return pathname === '/customers' ? 'customers' : pathname === '/orders' ? 'orders' : pathname === '/settings' ? 'settings' : 'dashboard' }
function localDateKey(date: Date) { return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}` }
function parsePrice(value: string) { return Number(value.replace(/\D/g, '')) }
function formatPriceInput(value: number) { return value ? rupiah.format(value) : '' }
function formatPriceTyping(value: string) { const digits = value.replace(/\D/g, ''); return digits ? rupiah.format(Number(digits)) : '' }
function loadReservations(email: string): Reservation[] { const saved = localStorage.getItem(bookingKey(email)); if (!saved) return []; try { return (JSON.parse(saved) as StoredReservation[]).map((item) => ({ ...item, checkIn: new Date(item.checkIn), checkOut: new Date(item.checkOut) })) } catch { return [] } }
function loadSettings() { try { const saved = localStorage.getItem('nafya-settings'); return saved ? JSON.parse(saved) as { notifications: boolean; compact: boolean; workspace: string } : { notifications: true, compact: false, workspace: 'Nafya Hotel Management' } } catch { localStorage.removeItem('nafya-settings'); return { notifications: true, compact: false, workspace: 'Nafya Hotel Management' } } }
function AuthGuard({ user }: { user: User | null }) { const location = useLocation(); if (user) return <Navigate to={location.pathname} replace />; return <Navigate to="/login" replace state={{ from: location }} /> }
function NotFound() { return <main className="not-found-page"><div className="not-found-card"><div className="eyebrow">KAWAN INAP HOTEL MANAGEMENT</div><strong className="not-found-code">404</strong><h1>Halaman tidak ditemukan</h1><p>Alamat yang Anda buka tidak tersedia atau sudah dipindahkan.</p><Link className="primary-button" to="/">Kembali ke Dashboard <ArrowUpRight size={17} /></Link></div></main> }
function Sidebar({ user, section, settings, count, open, onNavigate, onLogout }: { user: User; section: Section; settings: { workspace: string }; count: number; open: boolean; onNavigate: (section: Section) => void; onLogout: () => void }) { return <aside className={`sidebar ${open ? 'sidebar-open' : ''}`}><div className="brand"><img className="brand-wordmark" src="/kawan-inap-logo.svg" alt="Kawan Inap Sales Hotel Management" /></div><div className="workspace-label">{settings.workspace.toUpperCase()}</div><nav className="side-nav"><NavButton active={section === 'dashboard'} icon={<LayoutDashboard size={18} />} onClick={() => onNavigate('dashboard')}>Dashboard</NavButton><NavButton active={section === 'orders'} icon={<CalendarDays size={18} />} onClick={() => onNavigate('orders')}>Data Pesanan <span className="nav-count">{count}</span></NavButton><NavButton active={section === 'customers'} icon={<Users size={18} />} onClick={() => onNavigate('customers')}>Customers</NavButton><NavButton active={section === 'settings'} icon={<Settings size={18} />} onClick={() => onNavigate('settings')}>Pengaturan</NavButton></nav><div className="sidebar-bottom"><div className="help-card"><div className="help-icon">?</div><strong>Butuh bantuan?</strong><span>Hubungi tim support kami</span><button type="button">Pusat Bantuan <ArrowUpRight size={14} /></button></div><div className="profile-mini"><div className="avatar avatar-small">{user.initials}</div><div><strong>{user.name}</strong><span>{user.role}</span></div><button className="icon-button" type="button" onClick={onLogout} aria-label="Keluar"><LogOut size={16} /></button></div></div></aside> }
function NavButton({ active, icon, onClick, children }: { active: boolean; icon: ReactNode; onClick: () => void; children: ReactNode }) { return <button className={`nav-item ${active ? 'active' : ''}`} type="button" onClick={onClick}>{icon}{children}</button> }
function PasswordField({ name, value, onChange }: { name: string; value?: string; onChange?: (value: string) => void }) { const [visible, setVisible] = useState(false); return <div className="password-field"><input required name={name} minLength={name === 'password' ? 6 : undefined} type={visible ? 'text' : 'password'} value={value} onChange={onChange ? (event) => onChange(event.target.value) : undefined} /><button className="password-toggle" type="button" onClick={() => setVisible((current) => !current)} aria-label={visible ? 'Sembunyikan password' : 'Tampilkan password'}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div> }
function LoginScreen({ login, setLogin, error, onSubmit }: { login: { email: string; password: string }; setLogin: (value: { email: string; password: string }) => void; error: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <main className="login-page"><div className="login-brand"><img className="brand-wordmark" src="/kawan-inap-logo.svg" alt="Kawan Inap Sales Hotel Management" /></div><section className="login-card"><div className="eyebrow">KAWAN INAP HOTEL MANAGEMENT</div><h1>Sign in</h1><p>Gunakan akun Anda untuk melanjutkan ke dashboard.</p><form onSubmit={onSubmit}><label>Email<input required type="email" value={login.email} onChange={(event) => setLogin({ ...login, email: event.target.value })} /></label><label>Password<PasswordField name="password" value={login.password} onChange={(value) => setLogin({ ...login, password: value })} /></label>{error && <span className="login-error">{error}</span>}<button className="primary-button login-button" type="submit">Next <ArrowUpRight size={17} /></button></form><small>Demo: admin@nafya.com / admin123</small><div className="auth-link">Don't have an account? <Link to="/register">Sign up</Link></div></section></main> }
function RegisterScreen({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <main className="login-page"><div className="login-brand"><img className="brand-wordmark" src="/kawan-inap-logo.svg" alt="Kawan Inap Sales Hotel Management" /></div><section className="login-card"><div className="eyebrow">KAWAN INAP HOTEL MANAGEMENT</div><h1>Create account</h1><p>Buat akun untuk mengelola dashboard hotel Anda.</p><form onSubmit={onSubmit}><label>Nama lengkap<input required name="name" /></label><label>Email<input required name="email" type="email" /></label><label>Password<PasswordField name="password" /></label><button className="primary-button login-button" type="submit">Register <ArrowUpRight size={17} /></button></form><div className="auth-link">Already have an account? <Link to="/login">Sign in</Link></div></section></main> }
function StatCard({ title, value, icon, tone }: { title: string; value: string; icon: ReactNode; tone: string }) { return <article className={`stat-card ${tone}`}><div className="stat-head"><span>{title}</span><span className="stat-icon">{icon}</span></div><strong>{value}</strong><div className="stat-foot"><span className="trend">● Live</span><span>data terbaru</span></div></article> }
function Dashboard({ stats, trend, reservations, onAdd, onOrders, onDelete, onDetail }: { stats: { revenue: number; rooms: number; checkedIn: number }; trend: { day: string; value: number }[]; reservations: Reservation[]; onAdd: () => void; onOrders: () => void; onDelete: (id: string) => void; onDetail: (item: Reservation) => void }) { const hasTrendData = trend.some((item) => item.value > 0); const trendMax = Math.max(...trend.map((item) => item.value), 1); return <><section className="welcome-row"><div><div className="eyebrow">RINGKASAN OPERASIONAL</div><h1>Selamat datang kembali <span>✦</span></h1><p>Berikut ringkasan performa operasional hotel Anda hari ini.</p></div><button className="primary-button" type="button" onClick={onAdd}><Plus size={18} /> Tambah Pesanan</button></section><section className="stats-grid"><StatCard title="Total Pendapatan" value={rupiah.format(stats.revenue)} icon={<CircleDollarSign size={20} />} tone="revenue" /><StatCard title="Total Kamar Dipesan" value={`${stats.rooms} Kamar`} icon={<BedDouble size={20} />} tone="rooms" /><StatCard title="Tamu Sudah Check-In" value={`${stats.checkedIn} Tamu`} icon={<UserRound size={20} />} tone="guests" /></section><section className="chart-card"><div className="section-heading"><div><h2>Tren Pendapatan</h2><p>Sinkron dengan harga dan tanggal check-in pesanan.</p></div><span className="live-label"><i /> {hasTrendData ? 'Sinkron langsung' : 'Belum ada data'}</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={235}><AreaChart data={trend} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b23b55" stopOpacity={0.55} /><stop offset="70%" stopColor="#c86d55" stopOpacity={0.18} /><stop offset="100%" stopColor="#b23b55" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#f1d9df" strokeOpacity={0.12} strokeDasharray="4 5" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} domain={[0, trendMax]} tickFormatter={(value) => `${value}Jt`} /><Tooltip formatter={(value) => [rupiah.format(Number(value) * 1000000), 'Pendapatan']} /><Area type="monotone" dataKey="value" stroke="#cf5a62" strokeWidth={3} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div>{!hasTrendData && <div className="chart-empty">Belum ada pesanan pada rentang tanggal ini.</div>}</section><section className="orders-section"><div className="section-heading"><div><h2>Pesanan Terbaru</h2><p>Kelola dan pantau seluruh reservasi masuk.</p></div><button className="ghost-button" type="button" onClick={onOrders}>Lihat semua <ArrowUpRight size={15} /></button></div><ReservationTable reservations={reservations.slice(0, 5)} onEdit={() => undefined} onDetail={onDetail} onDelete={onDelete} /></section></> }
function OrdersPage({ reservations, filter, setFilter, onAdd, onEdit, onDetail, onDelete }: { reservations: Reservation[]; filter: 'Semua' | Status; setFilter: (value: 'Semua' | Status) => void; onAdd: () => void; onEdit: (item: Reservation) => void; onDetail: (item: Reservation) => void; onDelete: (id: string) => void }) {
  const [input, setInput] = useState('')
  const [submittedQuery, setSubmittedQuery] = useState('')
  const searchedReservations = useMemo(() => reservations.filter((item) => `${item.nama} ${item.hotel} ${item.nomorHp} ${item.id}`.toLowerCase().includes(submittedQuery.toLowerCase().trim())), [reservations, submittedQuery])
  const submitSearch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmittedQuery(input) }
  return <section className="page-panel"><div className="welcome-row"><div><div className="eyebrow">RESERVATION CENTER</div><h1>Data Pesanan</h1><p>Kelola seluruh reservasi dan status tamu.</p></div><button className="primary-button" type="button" onClick={onAdd}><Plus size={18} /> Tambah Pesanan</button></div><form className="orders-search" onSubmit={submitSearch}><Search size={17} /><input value={input} onChange={(event) => { const value = event.target.value; setInput(value); if (!value.trim()) setSubmittedQuery('') }} placeholder="Cari nama, hotel, nomor HP..." /><button className="search-submit" type="submit">Cari</button></form><div className="filter-bar"><span>Filter status:</span>{(['Semua', 'Belum Check In', 'Sudah Check In'] as const).map((status) => <button className={filter === status ? 'filter-active' : ''} type="button" key={status} onClick={() => setFilter(status)}>{status}</button>)}</div><ReservationTable reservations={searchedReservations} onEdit={onEdit} onDetail={onDetail} onDelete={onDelete} /></section>
}
function ReservationTable({ reservations, onEdit, onDetail, onDelete }: { reservations: Reservation[]; onEdit: (item: Reservation) => void; onDetail: (item: Reservation) => void; onDelete: (id: string) => void }) { return <div className="table-shell"><table><thead><tr><th>PEMESAN</th><th>HOTEL</th><th>CHECK-IN / JAM</th><th>HARGA</th><th>STATUS</th><th>AKSI</th></tr></thead><tbody>{reservations.map((item) => <tr key={item.id}><td><div className="customer"><div className="customer-avatar">{item.nama.slice(0, 2).toUpperCase()}</div><div><strong>{item.nama}</strong><span>#{item.id} · {item.nomorHp}</span></div></div></td><td><strong className="hotel-name">{item.hotel}</strong><span className="room-count">{item.kamar} kamar · checkout {dateFormat.format(item.checkOut)}</span></td><td><strong>{dateFormat.format(item.checkIn)}</strong><span className="date-arrow">·</span><strong>{item.jamMasuk}</strong></td><td><strong className="price">{rupiah.format(item.harga)}</strong></td><td><span className={`status-badge ${item.status === 'Sudah Check In' ? 'checked' : 'pending'}`}><i />{item.status}</span></td><td><div className="row-actions"><button className="delete-button" type="button" onClick={() => onDetail(item)} aria-label="Lihat detail"><Eye size={15} /></button><button className="delete-button" type="button" onClick={() => onEdit(item)} aria-label="Edit pesanan"><Pencil size={15} /></button><button className="delete-button" type="button" onClick={() => onDelete(item.id)} aria-label="Hapus pesanan"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table>{reservations.length === 0 && <div className="empty-state">Data tidak ditemukan.</div>}</div> }
function CustomersPage({ reservations, onEdit, onDelete }: { reservations: Reservation[]; onEdit: (item: Reservation) => void; onDelete: (id: string) => void }) { const customers = Array.from(new Map(reservations.map((item) => [item.id, item])).values()); return <section className="page-panel"><div className="eyebrow">CUSTOMER DIRECTORY</div><h1>Customers</h1><p>Seluruh customer pada akun yang sedang aktif.</p><div className="page-grid"><StatCard title="Pesanan ditemukan" value={String(customers.length)} icon={<Users size={20} />} tone="guests" /><StatCard title="Hotel partner" value={String(new Set(customers.map((item) => item.hotel)).size)} icon={<Hotel size={20} />} tone="rooms" /></div><div className="customer-table-wrap"><table><thead><tr><th>PELANGGAN</th><th>HOTEL</th><th>NOMOR HP</th><th>AKSI</th></tr></thead><tbody>{customers.map((item) => <tr key={item.id}><td><div className="customer"><div className="customer-avatar">{item.nama.slice(0, 2).toUpperCase()}</div><strong>{item.nama}</strong></div></td><td>{item.hotel}</td><td>{item.nomorHp}</td><td><div className="row-actions"><button className="delete-button" type="button" onClick={() => onEdit(item)} aria-label="Edit customer"><Pencil size={15} /></button><button className="danger-button" type="button" onClick={() => onDelete(item.id)}><Trash2 size={14} /> Hapus</button></div></td></tr>)}</tbody></table>{customers.length === 0 && <div className="empty-state">Data tidak ditemukan.</div>}</div></section> }
function SettingsPage({ settings, setSettings, onLogout }: { settings: { notifications: boolean; compact: boolean; workspace: string }; setSettings: (value: { notifications: boolean; compact: boolean; workspace: string }) => void; onLogout: () => void }) { const [draft, setDraft] = useState(settings.workspace); return <section className="page-panel"><div className="eyebrow">WORKSPACE SETTINGS</div><h1>Pengaturan</h1><p>Perubahan tersimpan otomatis di browser ini.</p><div className="settings-list"><div className="setting-row"><div><strong>Notifikasi pesanan</strong><span>Aktifkan pemberitahuan saat reservasi baru masuk.</span></div><input type="checkbox" checked={settings.notifications} onChange={(event) => setSettings({ ...settings, notifications: event.target.checked })} /></div><div className="setting-row"><div><strong>Mode tampilan kompak</strong><span>Gunakan jarak tabel yang lebih padat.</span></div><input type="checkbox" checked={settings.compact} onChange={(event) => setSettings({ ...settings, compact: event.target.checked })} /></div><div className="setting-row workspace-setting"><div><strong>Nama workspace</strong><span>{settings.workspace}</span></div><input value={draft} onChange={(event) => setDraft(event.target.value)} /><button className="ghost-button" type="button" onClick={() => draft.trim() && setSettings({ ...settings, workspace: draft.trim() })}>Simpan</button></div><div className="setting-row"><div><strong>Sesi akun</strong><span>Keluar dari dashboard pada perangkat ini.</span></div><button className="danger-button" type="button" onClick={onLogout}><LogOut size={15} /> Keluar</button></div></div></section> }
function ReservationModal({ form, editing, setForm, onClose, onSubmit }: { form: FormState; editing: boolean; setForm: (value: FormState) => void; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const update = (key: keyof FormState, value: string) => setForm({ ...form, [key]: value }); return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal" role="dialog" aria-modal="true"><div className="modal-header"><div><div className="eyebrow">{editing ? 'EDIT RESERVASI' : 'RESERVASI BARU'}</div><h2>{editing ? 'Edit Pesanan' : 'Tambah Pesanan'}</h2></div><button className="icon-button" type="button" onClick={onClose} aria-label="Tutup"><X size={20} /></button></div><form onSubmit={onSubmit}><div className="form-grid"><label>Nama pemesan<input required value={form.nama} onChange={(event) => update('nama', event.target.value)} /></label><label>Nomor HP<input required type="tel" value={form.nomorHp} onChange={(event) => update('nomorHp', event.target.value)} /></label><label>Nama hotel<input required value={form.hotel} onChange={(event) => update('hotel', event.target.value)} /></label><label>Harga (Rupiah)<input required min="0" inputMode="numeric" type="text" value={form.harga} onChange={(event) => update('harga', formatPriceTyping(event.target.value))} placeholder="Rp 20.000" /></label><label>Jumlah kamar<input required min="1" type="number" value={form.kamar} onChange={(event) => update('kamar', event.target.value)} /></label><label>Jam masuk<input required type="time" value={form.jamMasuk} onChange={(event) => update('jamMasuk', event.target.value)} /></label><label>Check-in<input required type="date" value={form.checkIn} onChange={(event) => update('checkIn', event.target.value)} /></label><label>Check-out<input required type="date" value={form.checkOut} onChange={(event) => update('checkOut', event.target.value)} /></label><label className="full-field">Status<select value={form.status} onChange={(event) => update('status', event.target.value as Status)}><option>Belum Check In</option><option>Sudah Check In</option></select></label></div><div className="modal-actions"><button className="ghost-button" type="button" onClick={onClose}>Batal</button><button className="primary-button" type="submit"><Check size={17} /> {editing ? 'Simpan Perubahan' : 'Simpan Pesanan'}</button></div></form></div></div> }
function DetailModal({ item, onClose }: { item: Reservation; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal detail-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><div className="eyebrow">DETAIL PESANAN #{item.id}</div><h2>{item.nama}</h2></div><button className="icon-button" type="button" onClick={onClose} aria-label="Tutup"><X size={20} /></button></div><div className="detail-grid"><div><span>Hotel</span><strong>{item.hotel}</strong></div><div><span>Status</span><strong>{item.status}</strong></div><div><span>Nomor HP</span><strong>{item.nomorHp}</strong></div><div><span>Harga</span><strong>{rupiah.format(item.harga)}</strong></div><div><span>Check-in</span><strong>{dateFormat.format(item.checkIn)} pukul {item.jamMasuk}</strong></div><div><span>Check-out</span><strong>{dateFormat.format(item.checkOut)}</strong></div><div><span>Kamar</span><strong>{item.kamar} kamar</strong></div></div><button className="primary-button" type="button" onClick={onClose}>Tutup detail</button></div></div> }

export default App
